### ISSUE TITLE
doesn't work on ubuntu

### ISSUE THREAD

**Issue by srl295** [devopstoolbox/openliberty#1]
doesn't have ubuntu support, see https://openliberty.io/blog/2020/04/09/microprofile-3-3-open-liberty-20004.html

**Comment by srl295** [comment]
I'm able to do a basic install as below, but not sure how to integrate this into your plugin.  I'm glad to submit a PR if i can!

```yaml
---
# tasks file for openliberty
# Docs here: https://openliberty.io/blog/2020/04/09/microprofile-3-3-open-liberty-20004.html#yum
- name: Install OpenLiberty GPG key
  become: true
  ansible.builtin.apt_key:
    url: http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/public.key
    state: present
  when:
    - ansible_distribution == "Ubuntu"
- name: Add OpenLiberty repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/deb/ /
    state: present
    filename: openliberty
- name: Install OpenLiberty packages
  become: true
  ansible.builtin.apt:
    pkg:
      - openliberty
```
